### ISSUE TITLE
Rolling Text does not reset for text not longer than container, gets stuck 

### ISSUE THREAD

**Issue by boovius** [Bang9/react-native-rolling-text#6]
![Simulator Screen Shot - iPhone 8 - 2022-06-14 at 12 38 36](https://user-images.githubusercontent.com/3697876/173674336-52c7df44-68dd-4c84-8b2d-7701e6881e64.png)

Our first shot here shows rolling text rolling with text. Then a button is clicked to change the text content while the first text is rolling off screen.

And yields this: 

![Simulator Screen Shot - iPhone 8 - 2022-06-14 at 12 36 00](https://user-images.githubusercontent.com/3697876/173674285-4f6c58af-6df7-4db6-ab48-d1d23f7634ce.png)

The rolling text stays stuck in its position and is not rendering the new text.

**Comment by bang9** [comment]
Hi @boovius ! thanks for the reporting.
[v0.0.2](https://github.com/bang9/react-native-rolling-text/releases/tag/0.0.2) is released!
